<?php 
// 此文件由命令生成
 return array (
  0 => 'admin_index',
  1 => 'admin_menu',
  2 => 'admin_welcome',
  3 => 'apps_onshelf',
  4 => 'apps_draft',
  5 => 'apps_pending',
  6 => 'apps_nopass',
  7 => 'apps_offshelf',
  8 => 'appsads.index',
  9 => 'appsads.create',
  10 => 'appsads.store',
  11 => 'appsads.edit',
  12 => 'appsads.update',
  13 => 'appsads.delete',
  14 => 'appsads.top',
  15 => 'appsads.notop',
  16 => 'appsads.onshelf',
  17 => 'appsads.offshelf',
  18 => 'appsads.index',
  19 => 'appsads.create',
  20 => 'appsads.delete',
  21 => 'appsads.index',
  22 => 'appsads.index',
  23 => 'appsads.index',
  24 => 'appsads.index',
);